name: Deploy Nodejs App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Actualizar Código y Reiniciar App
        run: |
          cd ~/aescimi
          git stash || true
          git pull origin main
          
          # Instalación de dependencias
          npm install --production
          
          # Reiniciar ambos servicios para aplicar cambios
          pm2 restart sena-backend
          pm2 restart sena-frontend
